
apiVersion: v1
kind: Service
metadata:
  name: app-staging
  namespace: default
  labels:
    app: app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:538812167457:certificate/888434dc-23c4-45f7-98a9-d7c9f7f3cfef
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443,80"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: https
    port: 443
    targetPort: 8080
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: app
    env: staging