
apiVersion: v1
kind: Service
metadata:
  name: app-staging
  namespace: default
  labels:
    app: app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: app
    env: staging